---
- name: Configure nginx proxy for FastAPI
  hosts: localhost
  connection: local
  become: yes

  vars:
    fastapi_port: 8001

  tasks:
    - name: Add FastAPI proxy to nginx config
      blockinfile:
        path: /etc/nginx/sites-available/baza-site
        marker: "# {mark} ANSIBLE MANAGED BLOCK - FastAPI"
        block: |
          # FastAPI proxy
          location /api/ {
              proxy_pass http://127.0.0.1:{{ fastapi_port }}/;
              proxy_set_header Host $host;
              proxy_set_header X-Real-IP $remote_addr;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_set_header X-Forwarded-Proto $scheme;
          }
        insertafter: "# Статические файлы"

    - name: Test nginx configuration
      command: nginx -t
      changed_when: false

    - name: Reload nginx
      systemd:
        name: nginx
        state: reloaded

    - name: Test proxy
      uri:
        url: http://127.0.0.1:8080/api/health
        method: GET
      register: proxy_test
      changed_when: false

    - name: Show proxy test result
      debug:
        msg: "Прокси работает: {{ proxy_test.status }}"
