---
- name: Install and configure PostgreSQL from Ubuntu repos
  hosts: localhost
  become: yes
  vars:
    postgres_password: "your_secure_password_123"
    postgres_db: "baza_db"
    postgres_user: "baza_user"
  
  tasks:
    - name: Install PostgreSQL
      apt:
        name: 
          - postgresql
          - postgresql-contrib
          - postgresql-client
          - libpq-dev
        state: present
        update_cache: yes

    - name: Ensure PostgreSQL is running
      systemd:
        name: postgresql
        state: started
        enabled: yes

    - name: Create database user
      become_user: postgres
      postgresql_user:
        name: "{{ postgres_user }}"
        password: "{{ postgres_password }}"
        state: present
        role_attr_flags: "CREATEDB,LOGIN"

    - name: Create database
      become_user: postgres
      postgresql_db:
        name: "{{ postgres_db }}"
        owner: "{{ postgres_user }}"
        state: present

    - name: Update PostgreSQL configuration to allow connections
      lineinfile:
        path: /etc/postgresql/*/main/postgresql.conf
        regexp: "^#?listen_addresses ="
        line: "listen_addresses = '*'"
        backup: yes

    - name: Update pg_hba.conf to allow password authentication
      lineinfile:
        path: /etc/postgresql/*/main/pg_hba.conf
        line: "host    all             all             0.0.0.0/0               md5"
        insertafter: EOF

    - name: Restart PostgreSQL
      systemd:
        name: postgresql
        state: restarted

    - name: Open PostgreSQL port in firewall
      ufw:
        rule: allow
        port: 5432
        proto: tcp

    - name: Show connection info
      debug:
        msg: |
          PostgreSQL installed successfully!
          Database: {{ postgres_db }}
          User: {{ postgres_user }}
          Password: {{ postgres_password }}
          Connection: psql -h localhost -U {{ postgres_user }} -d {{ postgres_db }}
