---
- name: Install PostgreSQL Simple
  hosts: localhost
  connection: local
  become: yes

  vars:
    db_name: "baza_db"
    db_user: "baza_user"
    db_password: "baza_password_123"

  tasks:
    - name: Install PostgreSQL
      apt:
        name:
          - postgresql
          - postgresql-contrib
        state: present

    - name: Start PostgreSQL service
      systemd:
        name: postgresql
        state: started
        enabled: yes

    - name: Create database using shell
      shell: |
        sudo -u postgres createdb {{ db_name }}
      args:
        executable: /bin/bash

    - name: Create user using shell
      shell: |
        sudo -u postgres psql -c \"CREATE USER {{ db_user }} WITH PASSWORD '{{ db_password }}';\"
      args:
        executable: /bin/bash

    - name: Grant privileges
      shell: |
        sudo -u postgres psql -c \"GRANT ALL PRIVILEGES ON DATABASE {{ db_name }} TO {{ db_user }};\"
      args:
        executable: /bin/bash

    - name: Create table
      shell: |
        sudo -u postgres psql -d {{ db_name }} -c \"
          CREATE TABLE IF NOT EXISTS items (
            id SERIAL PRIMARY KEY,
            name VARCHAR(100),
            price DECIMAL(10,2),
            created_at TIMESTAMP DEFAULT NOW()
          );
        \"
      args:
        executable: /bin/bash

    - name: Insert sample data
      shell: |
        sudo -u postgres psql -d {{ db_name }} -c \"
          INSERT INTO items (name, price) VALUES 
          ('Ноутбук', 1299.99),
          ('Телефон', 899.99)
          ON CONFLICT DO NOTHING;
        \"
      args:
        executable: /bin/bash

    - name: Test connection
      shell: |
        PGPASSWORD={{ db_password }} psql -h localhost -U {{ db_user }} -d {{ db_name }} -c \"SELECT version();\"
      register: test_result

    - name: Show result
      debug:
        msg: "PostgreSQL установлен: {{ test_result.stdout }}"
