---
- name: Install and configure PostgreSQL
  hosts: localhost
  become: yes
  vars:
    postgres_version: 15
    postgres_password: "your_secure_password_123"
    postgres_db: "baza_db"
    postgres_user: "baza_user"
  
  tasks:
    - name: Install PostgreSQL
      apt:
        name: 
          - postgresql-{{ postgres_version }}
          - postgresql-contrib-{{ postgres_version }}
          - postgresql-client-{{ postgres_version }}
          - libpq-dev
        state: present
        update_cache: yes

    - name: Ensure PostgreSQL is running
      systemd:
        name: postgresql
        state: started
        enabled: yes

    - name: Create database
      postgresql_db:
        name: "{{ postgres_db }}"
        state: present

    - name: Create user with password
      postgresql_user:
        name: "{{ postgres_user }}"
        password: "{{ postgres_password }}"
        db: "{{ postgres_db }}"
        priv: "ALL"
        state: present
        role_attr_flags: "CREATEDB,LOGIN"

    - name: Update PostgreSQL configuration to allow connections
      lineinfile:
        path: /etc/postgresql/{{ postgres_version }}/main/postgresql.conf
        regexp: "^#?listen_addresses ="
        line: "listen_addresses = '*'"
        backup: yes

    - name: Update pg_hba.conf to allow password authentication
      lineinfile:
        path: /etc/postgresql/{{ postgres_version }}/main/pg_hba.conf
        line: "host    all             all             0.0.0.0/0               md5"
        insertafter: EOF

    - name: Restart PostgreSQL
      systemd:
        name: postgresql
        state: restarted

    - name: Open PostgreSQL port in firewall
      ufw:
        rule: allow
        port: 5432
        proto: tcp
