---
- name: Install and configure PostgreSQL
  hosts: localhost
  become: yes
  vars:
    postgres_password: "your_secure_password_123"
    postgres_db: "baza_db"
    postgres_user: "baza_user"
  
  tasks:
    - name: Add PostgreSQL official repository
      apt_repository:
        repo: "deb https://apt.postgresql.org/pub/repos/apt {{ ansible_distribution_release }}-pgdg main"
        state: present
        filename: postgresql

    - name: Add PostgreSQL signing key
      apt_key:
        url: "https://www.postgresql.org/media/keys/ACCC4CF8.asc"
        state: present

    - name: Update package cache
      apt:
        update_cache: yes

    - name: Install PostgreSQL
      apt:
        name: 
          - postgresql-15
          - postgresql-contrib-15
          - postgresql-client-15
          - libpq-dev
        state: present

    - name: Ensure PostgreSQL is running
      systemd:
        name: postgresql
        state: started
        enabled: yes

    - name: Create database user
      become_user: postgres
      postgresql_user:
        name: "{{ postgres_user }}"
        password: "{{ postgres_password }}"
        state: present
        role_attr_flags: "CREATEDB,LOGIN"

    - name: Create database
      become_user: postgres
      postgresql_db:
        name: "{{ postgres_db }}"
        owner: "{{ postgres_user }}"
        state: present

    - name: Update PostgreSQL configuration to allow connections
      lineinfile:
        path: /etc/postgresql/15/main/postgresql.conf
        regexp: "^#?listen_addresses ="
        line: "listen_addresses = '*'"
        backup: yes

    - name: Update pg_hba.conf to allow password authentication
      lineinfile:
        path: /etc/postgresql/15/main/pg_hba.conf
        line: "host    all             all             0.0.0.0/0               md5"
        insertafter: EOF

    - name: Restart PostgreSQL
      systemd:
        name: postgresql
        state: restarted

    - name: Open PostgreSQL port in firewall
      ufw:
        rule: allow
        port: 5432
        proto: tcp
